api/v1/user/administrator/urls.py
from django.urls import path

from . import views

app_name = 'api_administrator'

urlpatterns = [
    path('applicants/list/', views.ApplicantsList.as_view(), name='applicants_list'),
    path('account/balance/', views.AccountBalance.as_view(), name='account_balance'),

]

api/v1/user/urls.py
from django.urls import path, include

from . import views

app_name = 'api_user'

urlpatterns = [
    path('auth/', include('djoser.urls')),
    path('auth/', include('djoser.urls.jwt')),

    path('login/', views.LoginView.as_view(), name='login_view'),

    path('detail/<int:pk>/', views.UserDetailView.as_view(), name='user_detail'),
    path('organizations/list/', views.UserOrganizationsList.as_view(), name='user_organizations_list'),
    path('<int:pk>/organizations/list/', views.OrganizationsList.as_view(), name='organizations_list'),
    path('car-models/list/', views.CarModelsList.as_view(), name='car_models_list'),
    path('car-colors/list/', views.CarColorsList.as_view(), name='car_colors_list'),
    path('car-types/list/', views.CarTypesList.as_view(), name='car_types_list'),
    path('devices/list/', views.DevicesList.as_view(), name='devices_list'),
    path('regions/list/', views.RegionsList.as_view(), name='regions_list'),
    path('section/exists/regions/list/', views.SectionExistsRegionsList.as_view(), name='section_exists_regions_list'),
    path('region/<int:pk>/districts/list/', views.RegionDistrictsList.as_view(), name='region_districts_list'),
    path('region/<int:pk>/sections/list/', views.RegionSectionsList.as_view(), name='region_sections_list'),
    path('district/<int:pk>/quarters/list/', views.DistrictQuartersList.as_view(), name='district_quarters_list'),
    path('car-fuel-types/list/', views.CarFuelTypesList.as_view(), name='car_fuel_types_list'),
    path('car-body-types/list/', views.CarBodyTypesList.as_view(), name='car_body_types_list'),
    path('create-organization/', views.CreateOrganization.as_view(), name='create_organization'),
    path('create-car-model/', views.CreateCarModel.as_view(), name='create_car_model'),
    path('create-color/', views.CreateColor.as_view(), name='create_color'),

    path('get-code/', views.GetCode.as_view(), name='get_code'),
    path('verify-code/', views.VerifyCode.as_view(), name='verify_code'),

    path('playmobile/sms/status/', views.PlayMobileSmsStatus.as_view()),

    path('get/card/phone/number/', views.GetCardPhoneNumber.as_view(), name='get_card_phone_number'),

    path('confirm/pay/', views.ConfirmPay.as_view(), name="confirm_pay"),

]

app/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

app_name = 'app'

urlpatterns = [
    path('home/', home, name='home'),
    path('new-car/', new_car, name='new_car'),
    path('word/', word, name='word'),

]

application/urls.py
from django.urls import path, include
from django.views.generic import TemplateView

from .views import *

app_name = 'application'

urlpatterns = [
    path('applications-list/', ApplicationsList.as_view(), name='applications_list'),

    # path('application-detail/<int:id>/', application_detail, name='application_detail2'),
    # path('application-detail/<int:id>/', ApplicationDetail.as_view(), name='application_detail'),

    path('application-detail/<int:id>/',
         TemplateView.as_view(template_name='application/application_detail_vue.html'), name='application_detail'),

    path('application-pdf/<int:id>/', ApplicationPdf.as_view(), name='application_pdf'),
    path('application-pay-status/<int:id>/', ApplicationPayStatus.as_view(), name='application_pay_status'),
    path('get-information/', get_information, name='get_information'),
    path('create-application-doc/<str:filename>/', create_application_doc, name='create_application_doc'),
    path('view-service-data/<int:service_id>/', view_service_data, name='view_service_data'),

    path('change-get-request/<str:key>/<str:value>/', change_get_request, name='change_get_request'),
    path('confirm-application-data/', ConfirmApplicationData.as_view(), name='confirm_application_data'),
    path('get-given-number/<int:id>/', GetGivenNumber.as_view(), name='get_given_number'),
    path('remove-application/', RemoveApplication.as_view(), name='remove_application'),

    path('payment-detail/<int:service_id>/', payment_detail, name='payment_detail'),

    path('payments-list/', PaymentsList.as_view(), name='payments_list'),
    path('modify-payment-checkbox/', Modify_Payment_Checkbox.as_view(), name='modify_payment_checkbox'),

    path('generate-qr-code-image/<int:id>/', generate_qr_code_image, name='generate_qr_code_image'),

    path('check-application-status/<int:id>/', check_application_status, name='check_application_status'),

    path('access-with-qrcode/<int:id>/', access_with_qrcode, name='access_with_qrcode'),

    path('section-applications-list/<int:section_id>/', SectionApplicationsList.as_view(),
         name='SectionApplicationsList'),

    path('save-application-section/', SaveApplicationSection.as_view(), name='save_application_section'),
    path('draft-to-shipped/<int:application_id>/', DraftToShipped.as_view(), name='draft_to_shipped'),

    path('application-cash-by-moderator/', ApplicationCashByModeratorView.as_view(),
         name='application_cash_by_moderator'),

    path('save-draft-application/', SaveDraftApplication.as_view(), name='save_draft_application'),

    path('payments-report/', PaymentsReport.as_view(), name='payments_report'),
    path('applicants-list/', ApplicantsList.as_view(), name='applicants_list'),
]

reception/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.http import HttpResponse
from django.shortcuts import redirect
from django.urls import path, include
from django.views.generic import TemplateView
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

from reception import settings
from user.views import HelloView, CustomAuthToken
from django.conf.urls.i18n import i18n_patterns


def trigger_error(request):
    division_by_zero = 1 / 0


urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('qish/', admin.site.urls),
    path('sentry-debug/', trigger_error),

    path('api/v1/', include('api.v1.urls')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    # path('api-token-auth/', CustomAuthToken.as_view(), name='api_token_auth'),
    path('payme/', include('paycom.urls')),
    path('click/', include('click.urls')),
    path('payments/', include('payments.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

urlpatterns += i18n_patterns(
    path('service/', include('service.urls')),
    path('help/', include('help.urls')),
    path('accounts/', include('allauth.urls')),
    path('', include('landing.urls')),
    path('user/', include('user.urls')),
    path('partners/', include('partners.urls')),
    path('application/', include('application.urls')),
    path('driver-license/', include('driver_license.urls')),
    path('error-403/', TemplateView.as_view(template_name='_parts/403.html', ),
         name='error_403'),
    path('error-404/', TemplateView.as_view(template_name='_parts/404.html', ),
         name='error_404'),
)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "user.views.handler404"

user/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from .views import *

app_name = 'user'

urlpatterns = [
    # signup, login, logout requests
    path('signup/', user_signup, name='signup'),
    path('login/', TemplateView.as_view(template_name='account/login.html'),
         name='login_view'),
    path('logout/', user_logout, name='logout'),
    path('custom-logout/', Logout.as_view(), name='custom_logout'),
    path('handler404/', handler404, name='handler404'),

    # other requests
    path('home/', Home.as_view(), name='home'),
    path('', personal_data, name='personal_data'),
    path('view-personal-data/<int:id>/', view_personal_data, name='view_personal_data'),
    path('edit-personal-data/', EditPersonalData.as_view(), name='edit_personal_data'),
    path('applicant/update/<int:pk>/', ApplicantUpdate.as_view(), name='applicant_update'),
    path('save-personal-data/', SavePersonalData.as_view(), name='save_personal_data'),
    path('add-organization/', add_organization, name='add_organization'),

    path('organizations-list/', OrganizationList.as_view(), name='organizations_list'),
    path('edit-organization/<int:organization_id>/', edit_organization, name='edit_organization'),
    path('remove-organization/', Remove_Organization.as_view(), name='remove_organization'),

    # ajax requests
    path('get-district/', get_district, name='get_district'),
    path('get-child-sections/', GetChildSections.as_view(), name='GetChildSections'),

    path('get-code/', GetCode.as_view(), name='get_code'),
    path('verify-code/', VerifyCode.as_view(), name='verify_code'),
    path('get-user-pass/', get_user_pass, name='get_user_pass'),
    path('forgot-pass/', forgot_pass, name='forgot_pass'),
    path('get-phone/', get_phone, name='get_phone'),
    path('is-register/', is_register, name='is_register'),
    path('get-organization/', Get_Organization.as_view(), name='get_organization'),
    # path('check_passport/', check_passport, name='check_passport'),
    # path('check_passport_with_number/', check_passport_with_number, name='check_passport_with_number'),
    path('save-user-information/', SaveUserInformation.as_view(), name='save_user_information'),
    path('save-user-passport/<int:pk>/', SaveUserPassport.as_view(), name='save_user_passport'),
    path('add-worker/', add_worker, name='add_worker'),
    path('workers-list/', workers_list, name='workers_list'),
    path('worker-delete/<int:worker_id>/', worker_delete, name='worker_delete'),
    path('worker-edit/<int:worker_id>/', worker_edit, name='worker_edit'),
    # path('view-car-data/<int:car_id>/', view_car_data, name='view_car_data'),
    path('view-car-data/<int:car_id>/', ViewCarData.as_view(), name='view_car_data'),
    # path('edit-car-data/<int:car_id>/', edit_car_data, name='edit_car_data'),
    path('edit-car-data/<int:car_id>/', EditCarData.as_view(), name='edit_car_data'),
    path('view-organization-data/<int:id>/', view_organization_data, name='view_organization_data'),
    path('confirm-car-data/<int:car_id>/', confirm_car_data, name='confirm_car_data'),

    # ajax requests
    path('get-car-type/', Get_Car_Type.as_view(), name='get_car_type'),
    path('save-new-car-model/', Save_New_Car_Model.as_view(), name='save_new_car_model'),
    path('save-new-color/', Save_New_Color.as_view(), name='save_new_color'),
    path('getDistricts/', getDistricts, name='getDistricts'),
    path('getQuarters/', getQuarters, name='getQuarters'),
    path('get_quarters/', get_quarters, name='get_quarters'),

    # STATE CONTROLLER
    path('regions-list/', regions_list, name='regions_list'),
    path('sections-list/<int:section_id>/', sections_list, name='sections_list'),
    path('sections-list-by-region/', SectionsListByRegion.as_view(), name='sections_list_by_region'),
    path('get-regions-list/', GetRegionsList.as_view(), name='get_regions_list'),
    path('get-sections-list/<int:region_id>/', GetSectionsList.as_view(), name='get_sections_list'),

    # path('section-districts-list/<int:section_id>/', section_districts_list, name='section_districts_list'),

    # app creatoe role
    path('create_user_account_view/', CreateUserAccountView.as_view(), name='create_user_account_view'),

    path('create/card/pay/', TemplateView.as_view(template_name='payments/apelsin.html'), name="create_card_pay")
]

api/v1/user/administrator/views.py
from rest_framework import generics, status
from rest_framework.pagination import LimitOffsetPagination
from rest_framework.response import Response
from rest_framework.views import APIView

from api.v1 import permissions
from reception.api import PaymentByRequisites, SUCCESS
from user.models import (User, USER, Balance)
from . import filters
from . import serializers
from api.v1.user.serializers import UserListSerializer


class ApplicantsList(generics.ListAPIView):
    queryset = User.objects.filter(is_active=True)
    serializer_class = UserListSerializer
    filter_class = filters.ApplicantsRightFilter
    pagination_class = LimitOffsetPagination
    max_page_size = 10

    permission_classes = [
        permissions.AdministratorPermission
    ]

    def get_queryset(self):
        qs = super(ApplicantsList, self).get_queryset().filter(is_superuser=False, is_staff=False,
                                                               role__in=[USER]).order_by('-id')
        return qs


class AccountBalance(APIView):
    def get(self, request, *args, **kwargs):
        account_balance = PaymentByRequisites().account_balance()
        if account_balance['status'] == SUCCESS:
            balance = int(account_balance['result']) / 100
            Balance.objects.create(amount=balance)
            return Response(balance, status=status.HTTP_200_OK)
        else:
            return Response(account_balance['result'], status=status.HTTP_400_BAD_REQUEST)

templates/user/role/administrator/applicants_list.html
{% extends 'base_vertical.html' %}
{% load static %}
{% load i18n %}

{% block show_left_bar %}  "size": "condensed"{% endblock show_left_bar %}

{% block css %}

    <!-- third party css -->
    <link href="{% static 'assets/libs/datatables.net-bs4/css/dataTables.bootstrap4.min.css' %}" rel="stylesheet"
          type="text/css"/>
    <link href="{% static 'assets/libs/datatables.net-responsive-bs4/css/responsive.bootstrap4.min.css' %}"
          rel="stylesheet" type="text/css"/>
    <link href="{% static 'assets/libs/datatables.net-buttons-bs4/css/buttons.bootstrap4.min.css' %}" rel="stylesheet"
          type="text/css"/>
    <link href="{% static 'assets/libs/datatables.net-select-bs4/css/select.bootstrap4.min.css' %}" rel="stylesheet"
          type="text/css"/>
    <!-- third party css end -->

{% endblock css %}

{% block page_title %}
    {% trans "Arizachilar" %}
{% endblock %}

{% block content %}

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-10 col-xs-12">
                            <table id="example1" class="table dt-responsive nowrap w-100">
                                <thead>
                                <tr>

                                    <th>{% trans "#" %}</th>
                                    <th>{% trans "Arizachi" %}</th>
                                    <th>{% trans "Viloyat" %}</th>
                                    <th>{% trans "Tuman/Shahar" %}</th>
                                    <th>{% trans "So'nggi tashrif" %}</th>
                                    <th>{% trans "Ro'yhatdan o'tgan" %}</th>
                                    <th>{% trans "Tahrirlash" %}</th>
                                    {#                                    <th>{% trans "Ariza raqami" %}</th>#}
                                </tr>
                                </thead>


                                <tbody>

                                </tbody>
                            </table>
                        </div>

                        <div class="col-md-2" id="right_filter_div">
                            {% include 'user/role/administrator/right_filter_applicants.html' %}
                        </div>
                    </div>


                </div> <!-- end card body-->
            </div> <!-- end card -->
        </div><!-- end col-->

    </div>

{% endblock content %}
{% block js %}
    <script src="{% static 'assets/libs/datatables.net/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'assets/libs/datatables.net-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'assets/libs/datatables.net-responsive/js/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'assets/libs/datatables.net-buttons/js/dataTables.buttons.min.js' %}"></script>
    <script src="{% static 'assets/libs/datatables.net-keytable/js/dataTables.keyTable.min.js' %}"></script>
    <script src="{% static 'assets/libs/datatables.net-select/js/dataTables.select.min.js' %}"></script>
    <script src="{% static 'assets/libs/pdfmake/build/pdfmake.min.js' %}"></script>
    <script src="{% static 'assets/libs/pdfmake/build/vfs_fonts.js' %}"></script>
    <script src="{% static 'assets/js/pages/datatables.init.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script src="{% static 'assets/libs/sweetalert/sweetalert.min.js' %}"></script>
    <script src="{% static 'assets/libs/moment/moment.js' %}"></script>
    <script src="{% static 'assets/libs/moment/locale/ru.js' %}"></script>
    <script type="text/javascript" class="init">
        $(document).ready(function () {
            sendAuthorizationToken()

            $.fn.dataTable.ext.errMode = function (settings, helpPage, message) {
                console.log(message);
            };

            var table = $("#example1").DataTable({
                "serverSide": true,
                "processing": true,
                'autoWidth': false,
                "orderCellsTop": true,
                "order": [[1, "asc"]],
                language: {
                    search: "_INPUT_",
                    searchPlaceholder: "{% trans 'Qidiruv...' %}",
                    "emptyTable": `{% trans "Ma'lumot topilmadi!" %}`,
                    {#"info": "Ko'rsatilgan _END_ dan _START_. Jami: _TOTAL_ ta ma'lumot",#}
                    "info": `{% trans "Jami: _TOTAL_ ta arizachi" %}`,
                    "infoEmpty": `{% trans "Jami: _TOTAL_ ta arizachi" %}`,
                    "infoFiltered": "(filtered from _MAX_ total entries)",
                    "infoPostFix": "",
                    "thousands": ",",
                    "lengthMenu": "_MENU_",
                    "loadingRecords": "{% trans 'Yuklanmoqda...' %}",
                    "processing": '<div class="spinner-grow" role="status"> <span class="sr-only"></span> </div>',
                    "zeroRecords": `{% trans "Ma'lumot topilmadi!" %}`,
                    "paginate": {
                        "first": "{% trans 'Birinchi' %}",
                        "last": "{% trans 'Oxirgi' %}",
                        "next": "{% trans 'Keyingi' %}",
                        "previous": "{% trans 'Oldingi' %}"
                    },
                    "aria": {
                        "sortAscending": `{% trans ": o'sish tartibi faollashtirildi" %}`,
                        "sortDescending": `{% trans ": kamayish tartibi faollashtirildi" %}`,
                    }
                },
                "ajax": function (data, callback, settings) {

                    $.ajax({
                        url: "{% url 'api_administrator:applicants_list' %}?id=475",
                        type: 'GET',
                        dataType: "json",
                        cache: false,
                        contentType: "application/json; charset=utf-8",
                        data: {
                            limit: data.length,
                            offset: data.start,
                            q: data.search.value,
                            order_by: data.columns[data.order[0].column].data.replace(/\./g, "__"),
                            old_request: window.location.search
                        }
                    }).then(function (res) {
                        console.log(res)
                        callback({
                            recordsTotal: res.count,
                            recordsFiltered: res.count,
                            data: res.results
                        });
                    });
                },
                "columns": [
                    {
                        data: "id",
                        orderable: false,
                        render: function (data, type, row) {
                            return data
                        }
                    },
                    {
                        "data": "phone",
                        render: function (data, type, row) {
                            return `<b>${row.last_name} ${row.first_name} ${row.middle_name}</b><br>+998${data}`
                        }
                    },
                    {
                        "data": 'region',
                        orderable: false,
                        render: function (data, type, row) {
                            return `<b>${data.title}</b>`
                        }
                    },
                    {
                        "data": 'district',
                        orderable: false,
                        render: function (data, type, row) {
                            return `<b>${data.title}</b>`
                        }
                    },
                    {
                        "data": "last_login",
                        render: function (data, type, row) {
                            moment.locale('ru');
                            return `<span title='${moment(data).format('LLL')}'>${moment(data).fromNow()}</span>`
                        }
                    },
                    {
                        "data": "date_joined",
                        render: function (data, type, row) {
                            moment.locale('ru');
                            return `<span title='${moment(data).format('LLL')}'>${moment(data).fromNow()}</span>`
                        }
                    },
                    {
                        "mData": null,
                        orderable: false,
                        "mRender": function (data, type, row) {
                            const href = "{% url 'user:applicant_update' 12345 %}".replace(/12345/, row.id.toString())
                            return `<a href="${href}" class="btn btn-outline-warning"><i class="fas fa-edit"></i></a>`

                        }
                    }
                    /*

                     {
                         "data": "created_date",
                         render: function (data, type, row) {
                             moment.locale('ru');
                             return `<span title='${moment(data).format('LLL')}'>${moment(data).fromNow()}</span>`
                         }
                     },
                     {
                         "data": "process",
                         render: function (data, type, row) {
                             if (row.process === 7) {
                                 return '<span class="badge label-table bg-warning">Ariza yaratilmoqda</span>'
                             } else if (row.process === 0) {
                                 return '<span class="badge label-table bg-warning">Ariza yaratilgan</span>'
                             } else if (row.process === 1) {
                                 return '<span class="badge label-table bg-info">YXHBga jo\'natilgan</span>'
                             } else if (row.process === 2) {
                                 return '<span class="badge label-table bg-info">Ko\'rib chiqilyapti</span>'
                             } else if (row.process === 3) {
                                 return '<span class="badge label-table bg-warning">To\'lov kutilmoqda</span>'
                             } else if (row.process === 4) {
                                 return '<span class="badge label-table bg-warning">Hujjatlarning asl nusxalari kutilmoqda</span>'
                             } else if (row.process === 5) {
                                 return '<span class="badge label-table bg-success">Muvaffaqiyatli yakunlangan</span>'
                             } else if (row.process === 6) {
                                 return '<span class="badge label-table bg-danger">Rad etilgan</span>'
                             }

                         }

                     },
                     {"data": "id"}, */
                ]
            })
        })
    </script>
{% endblock js %}

templates/user/role/administrator/right_filter_applicants.html
{% load applications_tags service_tags static %}
<style>

</style>

<div style="background-color: #e7fafd; border-radius: 5px" class="p-1">
    <h6 style="font-size: 0.8em; margin-bottom: 0.6em" class="font-10 text-muted text-uppercase">Viloyat
        bo'yicha</h6>
    <div class="p-1" style="font-size: 0.8em;">
        <a {% if request.GET.region == 'all' or not request.GET.region %}class="active" {% endif %}
           href="{% url "application:change_get_request" 'region' 'all' %}" class="text-reset d-block">
            <i class="mdi mdi-checkbox-blank-circle-outline me-1 text-success"></i>
            <span class="mb-0 mt-1">Hammasi</span>
        </a>
        <div id="right_filter_region_div">

        </div>
    </div>

    <h6 style="font-size: 0.8em; margin-bottom: 0.6em" class="font-10 text-muted text-uppercase">So'ngi tashrif bo'yicha</h6>
    <div class="p-1" style="font-size: 0.8em;">
        <a {% if request.GET.last_login == 'all' or not request.GET.last_login %}class="active" {% endif %}
           href="{% url "application:change_get_request" 'last_login' 'all' %}" class="text-reset d-block">
            <i class="mdi mdi-checkbox-blank-circle-outline me-1 text-success"></i>
            <span class="mb-0 mt-1">Istalgan kun</span></a>
        <a {% if request.GET.last_login == 'today' %}class="active" {% endif %}
           href="{% url "application:change_get_request" 'last_login' 'today' %}" class="text-reset d-block">
            <i class="mdi mdi-checkbox-blank-circle-outline me-1 text-success"></i>
            <span class="mb-0 mt-1">Bugun</span></a>
        <a {% if request.GET.last_login == 'last-7-days' %}class="active" {% endif %}
           href="{% url "application:change_get_request" 'last_login' 'last-7-days' %}" class="text-reset d-block">
            <i class="mdi mdi-checkbox-blank-circle-outline me-1 text-success"></i>
            <span class="mb-0 mt-1">So'nggi 7 kun</span></a>
        <a {% if request.GET.last_login == 'month' %}class="active" {% endif %}
           href="{% url "application:change_get_request" 'last_login' 'month' %}" class="text-reset d-block">
            <i class="mdi mdi-checkbox-blank-circle-outline me-1 text-success"></i>
            <span class="mb-0 mt-1">Shu oyda</span></a>
        <a {% if request.GET.last_login == 'year' %}class="active" {% endif %}
           href="{% url "application:change_get_request" 'last_login' 'year' %}" class="text-reset d-block">
            <i class="mdi mdi-checkbox-blank-circle-outline me-1 text-success"></i>
            <span class="mb-0 mt-1">Shu yilda</span></a>
    </div>

    <h6 style="font-size: 0.8em; margin-bottom: 0.6em" class="font-10 text-muted text-uppercase">Ro'yhatdan o'tish bo'yicha</h6>
    <div class="p-1" style="font-size: 0.8em;">
        <a {% if request.GET.date_joined == 'all' or not request.GET.date_joined %}class="active" {% endif %}
           href="{% url "application:change_get_request" 'date_joined' 'all' %}" class="text-reset d-block">
            <i class="mdi mdi-checkbox-blank-circle-outline me-1 text-success"></i>
            <span class="mb-0 mt-1">Istalgan kun</span></a>
        <a {% if request.GET.date_joined == 'today' %}class="active" {% endif %}
           href="{% url "application:change_get_request" 'date_joined' 'today' %}" class="text-reset d-block">
            <i class="mdi mdi-checkbox-blank-circle-outline me-1 text-success"></i>
            <span class="mb-0 mt-1">Bugun</span></a>
        <a {% if request.GET.date_joined == 'last-7-days' %}class="active" {% endif %}
           href="{% url "application:change_get_request" 'date_joined' 'last-7-days' %}" class="text-reset d-block">
            <i class="mdi mdi-checkbox-blank-circle-outline me-1 text-success"></i>
            <span class="mb-0 mt-1">So'nggi 7 kun</span></a>
        <a {% if request.GET.date_joined == 'month' %}class="active" {% endif %}
           href="{% url "application:change_get_request" 'date_joined' 'month' %}" class="text-reset d-block">
            <i class="mdi mdi-checkbox-blank-circle-outline me-1 text-success"></i>
            <span class="mb-0 mt-1">Shu oyda</span></a>
        <a {% if request.GET.date_joined == 'year' %}class="active" {% endif %}
           href="{% url "application:change_get_request" 'date_joined' 'year' %}" class="text-reset d-block">
            <i class="mdi mdi-checkbox-blank-circle-outline me-1 text-success"></i>
            <span class="mb-0 mt-1">Shu yilda</span></a>
    </div>
</div>

{% block js %}
    <script src="{% static 'assets/libs/jquery/jquery.min.js' %}" type="text/javascript"></script>
    <script type="text/javascript">
        $(function () {
            sendAuthorizationToken()


            getAjaxData("{% url 'api_user:regions_list' %}").then(res => {
                var a2 = ""
                var region_get = "{{ request.GET.region }}"
                res.forEach((x, i) => {
                    var href = "{% url "application:change_get_request" 'region' 12345 %}".replace(/12345/, x.id.toString())
                    a2 += `<a href=${href} class="${x.id.toString() === region_get ? 'active' : 'text-reset d-block'}">
                            <i class="mdi mdi-checkbox-blank-circle-outline me-1 text-success"></i>
                            <span class="mb-0 mt-1">${x.title}</span>
                            </a>`
                })
                $('#right_filter_region_div').html(a2)
            })
        })
    </script>
{% endblock js %}