api/v1/service/urls.py
from django.urls import path

from . import views

app_name = 'api_service'

urlpatterns = [
    path('list/', views.ServiceList.as_view(), name='services_list'),
    path('state-duty-percent/detail/<int:pk>/', views.StateDutyPercentDetail.as_view(),
         name='state_duty_percent_detail'),
    path('region/<int:id>/state-duties/report/', views.RegionStateDutiesReport.as_view(), name='region_state_duties_report'),
    path('payment-for-treasury/list/', views.PaymentForTreasuryList.as_view(), name='payment_for_treasury_list'),

]

api/v1/user/state_controller/urls.py
from django.urls import path

from . import views

app_name = 'api_state_controller'

urlpatterns = [
    path('applications/list/', views.ApplicationsList.as_view(), name='applications_list'),
    path('payments/list/', views.PaymentsList.as_view(), name='payments_list'),
    path('state-duties/report/', views.StateDutiesReport.as_view(),
         name='state_duties_report'),
]

api/v1/user/urls.py
from django.urls import path, include

from . import views

app_name = 'api_user'

urlpatterns = [
    path('auth/', include('djoser.urls')),
    path('auth/', include('djoser.urls.jwt')),

    path('login/', views.LoginView.as_view(), name='login_view'),

    path('detail/<int:pk>/', views.UserDetailView.as_view(), name='user_detail'),
    path('organizations/list/', views.UserOrganizationsList.as_view(), name='user_organizations_list'),
    path('<int:pk>/organizations/list/', views.OrganizationsList.as_view(), name='organizations_list'),
    path('car-models/list/', views.CarModelsList.as_view(), name='car_models_list'),
    path('car-colors/list/', views.CarColorsList.as_view(), name='car_colors_list'),
    path('car-types/list/', views.CarTypesList.as_view(), name='car_types_list'),
    path('devices/list/', views.DevicesList.as_view(), name='devices_list'),
    path('regions/list/', views.RegionsList.as_view(), name='regions_list'),
    path('section/exists/regions/list/', views.SectionExistsRegionsList.as_view(), name='section_exists_regions_list'),
    path('region/<int:pk>/districts/list/', views.RegionDistrictsList.as_view(), name='region_districts_list'),
    path('region/<int:pk>/sections/list/', views.RegionSectionsList.as_view(), name='region_sections_list'),
    path('district/<int:pk>/quarters/list/', views.DistrictQuartersList.as_view(), name='district_quarters_list'),
    path('car-fuel-types/list/', views.CarFuelTypesList.as_view(), name='car_fuel_types_list'),
    path('car-body-types/list/', views.CarBodyTypesList.as_view(), name='car_body_types_list'),
    path('create-organization/', views.CreateOrganization.as_view(), name='create_organization'),
    path('create-car-model/', views.CreateCarModel.as_view(), name='create_car_model'),
    path('create-color/', views.CreateColor.as_view(), name='create_color'),

    path('get-code/', views.GetCode.as_view(), name='get_code'),
    path('verify-code/', views.VerifyCode.as_view(), name='verify_code'),

    path('playmobile/sms/status/', views.PlayMobileSmsStatus.as_view()),

    path('get/card/phone/number/', views.GetCardPhoneNumber.as_view(), name='get_card_phone_number'),

    path('confirm/pay/', views.ConfirmPay.as_view(), name="confirm_pay"),

]

app/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

app_name = 'app'

urlpatterns = [
    path('home/', home, name='home'),
    path('new-car/', new_car, name='new_car'),
    path('word/', word, name='word'),

]

application/urls.py
from django.urls import path, include
from django.views.generic import TemplateView

from .views import *

app_name = 'application'

urlpatterns = [
    path('applications-list/', ApplicationsList.as_view(), name='applications_list'),

    # path('application-detail/<int:id>/', application_detail, name='application_detail2'),
    # path('application-detail/<int:id>/', ApplicationDetail.as_view(), name='application_detail'),

    path('application-detail/<int:id>/',
         TemplateView.as_view(template_name='application/application_detail_vue.html'), name='application_detail'),

    path('application-pdf/<int:id>/', ApplicationPdf.as_view(), name='application_pdf'),
    path('application-pay-status/<int:id>/', ApplicationPayStatus.as_view(), name='application_pay_status'),
    path('get-information/', get_information, name='get_information'),
    path('create-application-doc/<str:filename>/', create_application_doc, name='create_application_doc'),
    path('view-service-data/<int:service_id>/', view_service_data, name='view_service_data'),

    path('change-get-request/<str:key>/<str:value>/', change_get_request, name='change_get_request'),
    path('confirm-application-data/', ConfirmApplicationData.as_view(), name='confirm_application_data'),
    path('get-given-number/<int:id>/', GetGivenNumber.as_view(), name='get_given_number'),
    path('remove-application/', RemoveApplication.as_view(), name='remove_application'),

    path('payment-detail/<int:service_id>/', payment_detail, name='payment_detail'),

    path('payments-list/', PaymentsList.as_view(), name='payments_list'),
    path('modify-payment-checkbox/', Modify_Payment_Checkbox.as_view(), name='modify_payment_checkbox'),

    path('generate-qr-code-image/<int:id>/', generate_qr_code_image, name='generate_qr_code_image'),

    path('check-application-status/<int:id>/', check_application_status, name='check_application_status'),

    path('access-with-qrcode/<int:id>/', access_with_qrcode, name='access_with_qrcode'),

    path('section-applications-list/<int:section_id>/', SectionApplicationsList.as_view(),
         name='SectionApplicationsList'),

    path('save-application-section/', SaveApplicationSection.as_view(), name='save_application_section'),
    path('draft-to-shipped/<int:application_id>/', DraftToShipped.as_view(), name='draft_to_shipped'),

    path('application-cash-by-moderator/', ApplicationCashByModeratorView.as_view(),
         name='application_cash_by_moderator'),

    path('save-draft-application/', SaveDraftApplication.as_view(), name='save_draft_application'),

    path('payments-report/', PaymentsReport.as_view(), name='payments_report'),
    path('applicants-list/', ApplicantsList.as_view(), name='applicants_list'),
]

reception/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.http import HttpResponse
from django.shortcuts import redirect
from django.urls import path, include
from django.views.generic import TemplateView
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

from reception import settings
from user.views import HelloView, CustomAuthToken
from django.conf.urls.i18n import i18n_patterns


def trigger_error(request):
    division_by_zero = 1 / 0


urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('qish/', admin.site.urls),
    path('sentry-debug/', trigger_error),

    path('api/v1/', include('api.v1.urls')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    # path('api-token-auth/', CustomAuthToken.as_view(), name='api_token_auth'),
    path('payme/', include('paycom.urls')),
    path('click/', include('click.urls')),
    path('payments/', include('payments.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

urlpatterns += i18n_patterns(
    path('service/', include('service.urls')),
    path('help/', include('help.urls')),
    path('accounts/', include('allauth.urls')),
    path('', include('landing.urls')),
    path('user/', include('user.urls')),
    path('partners/', include('partners.urls')),
    path('application/', include('application.urls')),
    path('driver-license/', include('driver_license.urls')),
    path('error-403/', TemplateView.as_view(template_name='_parts/403.html', ),
         name='error_403'),
    path('error-404/', TemplateView.as_view(template_name='_parts/404.html', ),
         name='error_404'),
)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "user.views.handler404"

user/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from .views import *

app_name = 'user'

urlpatterns = [
    # signup, login, logout requests
    path('signup/', user_signup, name='signup'),
    path('login/', TemplateView.as_view(template_name='account/login.html'),
         name='login_view'),
    path('logout/', user_logout, name='logout'),
    path('custom-logout/', Logout.as_view(), name='custom_logout'),
    path('handler404/', handler404, name='handler404'),

    # other requests
    path('home/', Home.as_view(), name='home'),
    path('', personal_data, name='personal_data'),
    path('view-personal-data/<int:id>/', view_personal_data, name='view_personal_data'),
    path('edit-personal-data/', EditPersonalData.as_view(), name='edit_personal_data'),
    path('applicant/update/<int:pk>/', ApplicantUpdate.as_view(), name='applicant_update'),
    path('save-personal-data/', SavePersonalData.as_view(), name='save_personal_data'),
    path('add-organization/', add_organization, name='add_organization'),

    path('organizations-list/', OrganizationList.as_view(), name='organizations_list'),
    path('edit-organization/<int:organization_id>/', edit_organization, name='edit_organization'),
    path('remove-organization/', Remove_Organization.as_view(), name='remove_organization'),

    # ajax requests
    path('get-district/', get_district, name='get_district'),
    path('get-child-sections/', GetChildSections.as_view(), name='GetChildSections'),

    path('get-code/', GetCode.as_view(), name='get_code'),
    path('verify-code/', VerifyCode.as_view(), name='verify_code'),
    path('get-user-pass/', get_user_pass, name='get_user_pass'),
    path('forgot-pass/', forgot_pass, name='forgot_pass'),
    path('get-phone/', get_phone, name='get_phone'),
    path('is-register/', is_register, name='is_register'),
    path('get-organization/', Get_Organization.as_view(), name='get_organization'),
    # path('check_passport/', check_passport, name='check_passport'),
    # path('check_passport_with_number/', check_passport_with_number, name='check_passport_with_number'),
    path('save-user-information/', SaveUserInformation.as_view(), name='save_user_information'),
    path('save-user-passport/<int:pk>/', SaveUserPassport.as_view(), name='save_user_passport'),
    path('add-worker/', add_worker, name='add_worker'),
    path('workers-list/', workers_list, name='workers_list'),
    path('worker-delete/<int:worker_id>/', worker_delete, name='worker_delete'),
    path('worker-edit/<int:worker_id>/', worker_edit, name='worker_edit'),
    # path('view-car-data/<int:car_id>/', view_car_data, name='view_car_data'),
    path('view-car-data/<int:car_id>/', ViewCarData.as_view(), name='view_car_data'),
    # path('edit-car-data/<int:car_id>/', edit_car_data, name='edit_car_data'),
    path('edit-car-data/<int:car_id>/', EditCarData.as_view(), name='edit_car_data'),
    path('view-organization-data/<int:id>/', view_organization_data, name='view_organization_data'),
    path('confirm-car-data/<int:car_id>/', confirm_car_data, name='confirm_car_data'),

    # ajax requests
    path('get-car-type/', Get_Car_Type.as_view(), name='get_car_type'),
    path('save-new-car-model/', Save_New_Car_Model.as_view(), name='save_new_car_model'),
    path('save-new-color/', Save_New_Color.as_view(), name='save_new_color'),
    path('getDistricts/', getDistricts, name='getDistricts'),
    path('getQuarters/', getQuarters, name='getQuarters'),
    path('get_quarters/', get_quarters, name='get_quarters'),

    # STATE CONTROLLER
    path('regions-list/', regions_list, name='regions_list'),
    path('sections-list/<int:section_id>/', sections_list, name='sections_list'),
    path('sections-list-by-region/', SectionsListByRegion.as_view(), name='sections_list_by_region'),
    path('get-regions-list/', GetRegionsList.as_view(), name='get_regions_list'),
    path('get-sections-list/<int:region_id>/', GetSectionsList.as_view(), name='get_sections_list'),

    # path('section-districts-list/<int:section_id>/', section_districts_list, name='section_districts_list'),

    # app creatoe role
    path('create_user_account_view/', CreateUserAccountView.as_view(), name='create_user_account_view'),

    path('create/card/pay/', TemplateView.as_view(template_name='payments/apelsin.html'), name="create_card_pay")
]

api/v1/user/state_controller/views.py
import datetime

from django.db.models import Sum, F
from rest_framework import generics, status
from rest_framework.pagination import LimitOffsetPagination
from rest_framework.response import Response
from rest_framework.views import APIView

from application.models import (Application, ACCEPTED_FOR_CONSIDERATION, WAITING_FOR_PAYMENT,
                                WAITING_FOR_ORIGINAL_DOCUMENTS, REJECTED, ACCEPTED)
from reception.settings import LOCAL_TIMEZONE
from service.models import PaymentForTreasury, STATE_DUTY_TITLE
from . import serializers
from api.v1 import permissions
from application.models import (SHIPPED)
from .import filters
from ...filters import PaymentsListFilter
from ...serializers import PaymentForTreasuryListSerializer


class ApplicationsList(generics.ListAPIView):
    queryset = Application.objects.filter(is_active=True)
    serializer_class = serializers.ApplicationsListSerializer
    filter_class = filters.ApplicationRightFilter
    pagination_class = LimitOffsetPagination
    max_page_size = 10

    permission_classes = [
        permissions.StateControllerPermission
    ]

    def get_queryset(self):
        qs = super(ApplicationsList, self).get_queryset()
        return qs


class PaymentsList(generics.ListAPIView):
    queryset = PaymentForTreasury.objects.filter(is_active=True)
    serializer_class = PaymentForTreasuryListSerializer
    filter_class = PaymentsListFilter
    pagination_class = LimitOffsetPagination
    max_page_size = 10

    permission_classes = [
        permissions.RegionalControllerPermission |
        permissions.StateControllerPermission
    ]

    def get_queryset(self):
        qs = super().get_queryset().filter(status__in=[PaymentForTreasury.SUCCESS,
                                                       PaymentForTreasury.CANCELED,
                                                       PaymentForTreasury.FAILED])
        return qs


class StateDutiesReport(APIView):
    permission_classes = [
        permissions.RegionalControllerPermission |
        permissions.StateControllerPermission
    ]
    serializer_class = PaymentForTreasuryListSerializer

    def get_queryset(self, request, *args, **kwargs):
        qs = PaymentForTreasury.objects.filter(is_active=True, status=PaymentForTreasury.SUCCESS,
                                               memorial__isnull=False)
        region_id = request.GET.get('region')
        section_id = request.GET.get('section')
        start_date = request.GET.get('start_date')
        end_date = request.GET.get('end_date')

        # today_min = timezone.now().replace(tzinfo=LOCAL_TIMEZONE, hour=0, minute=0, second=0)
        # today_max = timezone.now().replace(tzinfo=LOCAL_TIMEZONE, hour=23, minute=59, second=59)

        if region_id:
            qs = qs.filter(application__section__region_id=region_id)

        if section_id:
            qs = qs.filter(application__section_id=section_id)

        start_min = datetime.datetime.strptime(start_date, "%Y-%m-%d").replace(tzinfo=LOCAL_TIMEZONE) if start_date else datetime.datetime.now().replace(tzinfo=LOCAL_TIMEZONE, day=1, month=1, year=2020)
        end_max = datetime.datetime.strptime(end_date, "%Y-%m-%d").replace(tzinfo=LOCAL_TIMEZONE) if end_date else datetime.datetime.now().replace(tzinfo=LOCAL_TIMEZONE)
        qs = qs.filter(created_at__range=[start_min, end_max])
        return qs

    def get(self, request, *args, **kwargs):
        # for title, items in itertools.groupby(qs, lambda x: dict(STATE_DUTY_TITLE).get(x.state_duty_percent.state_duty)):
        # for q in qs:
        #     state_duties.setdefault(q.state_duty_percent.get_state_duty_display(), []).append(q)
        results = self.get_queryset(request, *args, **kwargs).values(title=F('state_duty_percent__state_duty')) \
            .order_by('title') \
            .annotate(total_amount=Sum('amount'))

        for result in results:
            result['title'] = dict(STATE_DUTY_TITLE).get(result['title'])
        return Response(list(results), status=status.HTTP_200_OK)

templates/user/role/state_controller/payments_list.html
{% extends 'base_vertical.html' %}
{% load static %}
{% load i18n %}

{% block show_left_bar %}  "size": "condensed"{% endblock show_left_bar %}

{% block css %}

    <!-- third party css -->
    <link href="{% static 'assets/libs/datatables.net-bs4/css/dataTables.bootstrap4.min.css' %}" rel="stylesheet"
          type="text/css"/>
    <link href="{% static 'assets/libs/datatables.net-responsive-bs4/css/responsive.bootstrap4.min.css' %}"
          rel="stylesheet" type="text/css"/>
    <link href="{% static 'assets/libs/datatables.net-buttons-bs4/css/buttons.bootstrap4.min.css' %}" rel="stylesheet"
          type="text/css"/>
    <link href="{% static 'assets/libs/datatables.net-select-bs4/css/select.bootstrap4.min.css' %}" rel="stylesheet"
          type="text/css"/>
    <!-- third party css end -->

{% endblock css %}

{% block page_title %}
    {% if section %}{% blocktrans with section_title=section.title %}{{ section_title }}ga kelib
        tushgan arizalar{% endblocktrans %}{% else %}{% trans "Arizalar" %}{% endif %}
{% endblock %}

{% block content %}

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-12 col-xs-12">
                            <table id="example1" class="table dt-responsive nowrap w-100">
                                <thead>
                                <tr>
                                    <th>{% trans "Davlat boji" %}</th>
                                    <th>{% trans "Arizachi" %}</th>
                                    <th>{% trans "Xizmat turi" %}</th>
                                    <th>{% trans "YHXB RIB" %}</th>
                                    <th>{% trans "To'lov summasi" %}</th>
                                    <th>{% trans "Status" %}</th>
                                    <th>{% trans "r/s" %}</th>
                                    <th>{% trans "Yaratilgan vaqti" %}</th>

                                </tr>
                                </thead>


                                <tbody>

                                </tbody>
                            </table>
                        </div>
                    </div>


                </div> <!-- end card body-->
            </div> <!-- end card -->
        </div><!-- end col-->

    </div>

{% endblock content %}
{% block js %}
    <script src="{% static 'assets/libs/datatables.net/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'assets/libs/datatables.net-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'assets/libs/datatables.net-responsive/js/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'assets/libs/datatables.net-buttons/js/dataTables.buttons.min.js' %}"></script>
    <script src="{% static 'assets/libs/datatables.net-keytable/js/dataTables.keyTable.min.js' %}"></script>
    <script src="{% static 'assets/libs/datatables.net-select/js/dataTables.select.min.js' %}"></script>
    <script src="{% static 'assets/js/pages/datatables.init.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script src="{% static 'assets/libs/sweetalert2/sweetalert2.all.min.js' %}"></script>
    <script src="{% static 'assets/libs/bootstrap-notify/bootstrap-notify.min.js' %}"></script>
    <script src="{% static 'assets/libs/moment/moment.js' %}"></script>
    <script src="{% static 'assets/libs/moment/locale/ru.js' %}"></script>
    <script type="text/javascript" class="init">
        $(document).ready(function () {
            sendAuthorizationToken()

            $.fn.dataTable.ext.errMode = function (settings, helpPage, message) {
                console.log(message);
            };


            var table = $("#example1").DataTable({
                "serverSide": true,
                "processing": true,
                'autoWidth': false,
                "orderCellsTop": true,
                "order": [[5, "desc"]],
                language: {
                    search: "_INPUT_",
                    searchPlaceholder: "{% trans 'Qidiruv...' %}",
                    "emptyTable": `{% trans "Ma'lumot topilmadi!" %}`,
                    {#"info": "Ko'rsatilgan _END_ dan _START_. Jami: _TOTAL_ ta ma'lumot",#}
                    "info": `{% trans "Jami: _TOTAL_ ta ariza" %}`,
                    "infoEmpty": `{% trans "Jami: _TOTAL_ ta ariza" %}`,
                    "infoFiltered": "(filtered from _MAX_ total entries)",
                    "infoPostFix": "",
                    "thousands": ",",
                    "lengthMenu": "_MENU_",
                    "loadingRecords": "{% trans 'Yuklanmoqda...' %}",
                    "processing": '<div class="spinner-grow" role="status"> <span class="sr-only"></span> </div>',
                    "zeroRecords": `{% trans "Ma'lumot topilmadi!" %}`,
                    "paginate": {
                        "first": "{% trans 'Birinchi' %}",
                        "last": "{% trans 'Oxirgi' %}",
                        "next": "{% trans 'Keyingi' %}",
                        "previous": "{% trans 'Oldingi' %}"
                    },
                    "aria": {
                        "sortAscending": `{% trans ": o'sish tartibi faollashtirildi" %}`,
                        "sortDescending": `{% trans ": kamayish tartibi faollashtirildi" %}`,
                    }
                },
                "ajax": function (data, callback, settings) {
                    $.ajax({
                        url: "{% url 'api_state_controller:payments_list' %}",
                        type: 'GET',
                        dataType: "json",
                        cache: false,
                        contentType: "application/json; charset=utf-8",
                        data: {
                            limit: data.length,
                            offset: data.start,
                            q: data.search.value,
                            order_by: `${data.columns[data.order[0].column].data.replace(/\./g, "__")}:${data.order[0].dir}`,
                            old_request: window.location.search
                        }
                    }).then(function (res) {
                        callback({
                            recordsTotal: res.count,
                            recordsFiltered: res.count,
                            data: res.results
                        });
                    });
                },
                "columns": [
                    {
                        "data": "state_duty_title",
                        render: function (data, type, row) {
                            if (data) {
                                return data
                            } else {
                                return ''
                            }

                        }
                    },
                    {
                        "data": "applicant",
                        orderable: false,
                        render: function (data, type, row) {
                            var applicant_url = "{% url 'user:view_personal_data' 12345 %}".replace(/12345/, data.id.toString())

                            let applicant = `<a href='${applicant_url}'>${data.last_name} ${data.first_name} ${data.middle_name}</a>`
                            let organization = ''

                            if (row.organization) {
                                let organization_url = "{% url 'user:view_organization_data' 12345 %}".replace(/12345/, row.organization.id.toString())
                                organization = `<a href="${organization_url}">${row.organization.title}</a>`
                            }
                            return `${applicant} <br> ${organization ? organization + '<br>' : ''}  +998${data.phone}`
                        }
                    },
                    {
                        "data": "application",
                        orderable: false,
                        render: function (data, type, row) {
                            var url = "{% url 'application:application_detail' 12345 %}".replace(/12345/, data.id.toString())
                            return `<a href="${url}">${data.service.short_title}</a>`
                        }
                    },
                    {
                        "data": "district",
                        orderable: false,
                        render: function (data, type, row) {
                            try {
                                return row.application.section.title
                            } catch {
                                return ''
                            }

                        }
                    },

                    {
                        "data": "amount",
                        render: function (data, type, row) {
                            return formatMoney(data)
                        }
                    },
                    {
                        "data": 'status',
                        orderable: false,
                        render: function (data, type, row) {
                            if (data === 'success') {
                                return `<span class="badge label-table bg-success">${data}</span>`
                            } else if (data === 'failed') {
                                return `<span class="badge label-table bg-danger">${data}</span>`
                            } else if (data === 'processing') {
                                return `<span class="badge label-table bg-warning">${data}</span>`
                            } else if (data === 'canceled') {
                                return `<span class="badge label-table bg-danger">${data}</span>`
                            }

                        }
                    },
                    {
                        "data": 'state_duty_score',
                        orderable: false,
                        render: function (data, type, row) {
                            return data.score
                        }
                    },
                    {
                        "data": "created_at",
                        render: function (data, type, row) {
                            moment.locale('ru');
                            return `<span title='${moment(data).format('LLL')}'>${moment(data).fromNow()}</span>`
                        }
                    },
                    /*{
                         data: null,
                         className: "center",
                         defaultContent: `<button data-id="${row.id}" class="btn btn-success confirm_pay">To'lash</button>`
                     },*/
                ],
                /* createdRow: function (row, data, index) {
                     console.log(205, row)
                     if ((data.process === 2) || (data.process === 3) || (data.process === 4)) {
                         $(row).addClass('tr-warning')
                     } else if (data.process === 5) {
                         $(row).addClass('tr-success')
                     } else if (data.process === 6) {
                         $(row).addClass('tr-danger')
                     }
                 } */
            })
        })

        $('#exmaple1').on('change', function () {
            column_asc_desc()
        })

        $(document).on('click', '.confirm_pay', function () {
            const Button = $(this)

            Button.prop('disabled', true)
            const ButtonValue = Button.text()
            Button.html(`${ButtonValue}&nbsp<i class="fas fa-spinner fa-spin"></i>`)

            $.ajax({
                type: "POST",
                url: "{% url 'api_moderator:confirm_theasury_payment' %}",
                data: {
                    id: $(this).data('id')
                },
                success: function (res) {
                    console.log(res)

                    const Toast = Swal.mixin({
                        toast: true,
                        position: 'top-end',
                        showConfirmButton: false,
                        background: '#8ff8ac',
                        timer: 5000,
                        timerProgressBar: false,
                        didOpen: (toast) => {
                            toast.addEventListener('mouseenter', Swal.stopTimer)
                            toast.addEventListener('mouseleave', Swal.resumeTimer)
                        },
                    })
                    Toast.fire({
                        icon: 'success',
                        title: 'To\'lov muffaqiyatli amalga oshirildi!'
                    })
                    setTimeout(function () {
                        location.reload()
                    }, 5000)

                },
                error: function (err) {
                    swal_error(err)

                    Button.prop('disabled', false)
                    Button.html(ButtonValue)
                }
            })
        })
    </script>
{% endblock js %}