app/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

app_name = 'app'

urlpatterns = [
    path('home/', home, name='home'),
    path('new-car/', new_car, name='new_car'),
    path('word/', word, name='word'),

]

help/urls.py
from django.urls import path

from . import views

app_name = 'help'

urlpatterns = [
    path('', views.SectionsList.as_view(), name='sections_list_url'),
    path('section/<slug:slug>', views.SectionDetail.as_view(), name='section_detail_url'),
    path('search/', views.HelpfulArticleSearchView.as_view(), name='search'),

    path('detail/<slug>', views.HelpArticleDetailView.as_view(), name='article_detail_url'),
    path('set-helpful/', views.set_helpful, name='set_helpful'),
]

reception/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.http import HttpResponse
from django.shortcuts import redirect
from django.urls import path, include
from django.views.generic import TemplateView
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

from reception import settings
from user.views import HelloView, CustomAuthToken
from django.conf.urls.i18n import i18n_patterns


def trigger_error(request):
    division_by_zero = 1 / 0


urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('qish/', admin.site.urls),
    path('sentry-debug/', trigger_error),

    path('api/v1/', include('api.v1.urls')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    # path('api-token-auth/', CustomAuthToken.as_view(), name='api_token_auth'),
    path('payme/', include('paycom.urls')),
    path('click/', include('click.urls')),
    path('payments/', include('payments.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

urlpatterns += i18n_patterns(
    path('service/', include('service.urls')),
    path('help/', include('help.urls')),
    path('accounts/', include('allauth.urls')),
    path('', include('landing.urls')),
    path('user/', include('user.urls')),
    path('partners/', include('partners.urls')),
    path('application/', include('application.urls')),
    path('driver-license/', include('driver_license.urls')),
    path('error-403/', TemplateView.as_view(template_name='_parts/403.html', ),
         name='error_403'),
    path('error-404/', TemplateView.as_view(template_name='_parts/404.html', ),
         name='error_404'),
)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "user.views.handler404"

help/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models
from user.models import User

# Create your models here.


class HelpSection(models.Model):
    title = models.CharField(max_length=255, db_index=True)
    meta_desc = models.CharField(max_length=255, db_index=True, blank=True)
    meta_key = models.CharField(max_length=255, db_index=True, blank=True)
    slug = models.SlugField(unique=True)
    pub_date = models.DateTimeField(auto_now_add=True)
    sort = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Bo'lim"
        verbose_name_plural = "Bo'limlar"


class HelpArticle(models.Model):
    # section = models.ForeignKey(HelpSection, on_delete=models.CASCADE, related_name='%(app_label)s_%(class)s_articles', verbose_name="Bo'lim")
    section = models.ForeignKey(HelpSection, on_delete=models.CASCADE, related_name='articles')
    view = models.IntegerField(default=1)
    pub_date = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=255, db_index=True)
    meta_desc = models.CharField(max_length=255, db_index=True, blank=True)
    meta_key = models.CharField(max_length=255, db_index=True, blank=True)
    text = RichTextUploadingField()
    updated_date = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    slug = models.SlugField(unique=True)
    sort = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Maqola"
        verbose_name_plural = "Maqolalar"


class Helpful(models.Model):
    help_article = models.ForeignKey(HelpArticle, verbose_name="Maqola", on_delete=models.CASCADE)
    ip = models.GenericIPAddressField("Ip manzil", max_length=20)
    status = models.BooleanField("Holati", default=False)

    def __str__(self):
        return self.ip

    class Meta:
        verbose_name = "Baho"
        verbose_name_plural = "Baholar"


'''
populate_from=lambda instance: instance.title,
                       unique_with=['pub_date__month'],
                       slugify=lambda value: default_slugify(value.replace(' ','-').lower().replace(' ', '-').replace('а', 'a').replace('б', 'b').replace('в','v').replace('г', 'g').replace('д', 'd').replace('е', 'e').replace('ё', 'yo').replace( 'ж', 'zh').replace('з', 'z').replace('и', 'i').replace('й', 'j').replace('к', 'k').replace('л', 'l').replace('м', 'm').replace('н', 'n').replace('о', 'o').replace('п', 'p').replace('р', 'r').replace('с', 's').replace('т', 't').replace('у', 'u').replace('ф', 'f').replace('х', 'kh').replace('ц', 'ts').replace( 'ч', 'ch').replace('ш', 'sh').replace('щ', 'shch').replace('ы', 'i').replace('э', 'e').replace('ю', 'yu').replace('я', 'ya').replace('ь', '').replace(',', '').replace('.', '').replace('.', '')), editable=True, blank=True    '''

help/forms.py
from django import forms

from help.models import Helpful


class HelpfulForm(forms.ModelForm):
    class Meta:
        model = Helpful

        fields = ['status', 'help_article', 'ip']

help/views.py
from django.conf import settings
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views import generic
from django.views.generic import ListView, DetailView

from .forms import HelpfulForm
from .models import *


class SectionsList(ListView):
    model = HelpSection
    template_name = 'help/help/home.html'

    def get_queryset(self):
        self.sections = HelpSection.objects.all()
        return self.sections

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context = {
            'sections': self.sections,
        }
        return context


class SectionDetail(DetailView):
    model = HelpSection
    template_name = 'help/help/section_detail.html'
    context_object_name = 'section'
    slug_field = 'slug'

    def get_context_data(self, **kwargs):
        section = HelpSection.objects.get(slug=self.kwargs['slug'], )
        context = {
            'section': section,
        }
        return super(SectionDetail, self).get_context_data(**kwargs, **context)


class HelpfulArticleSearchView(ListView):
    template_name = 'help/help/search.html'
    context_object_name = "results"

    def get_queryset(self):
        query = self.request.GET.get('q')
        return HelpArticle.objects.filter(
            Q(title__icontains=query) | Q(text__icontains=query) | Q(
                text__icontains=query))

    # def get_context_data(self, *, object_list=None, **kwargs):
    #     article = HelpArticle.objects.filter(slug__icontains=)
    #     context = {
    #         'article': article
    #     }


class HelpArticleDetailView(DetailView):
    model = HelpArticle
    slug_field = "slug"
    template_name = 'help/help/article_detail.html'

    def get_context_data(self, **kwargs):
        slug = self.kwargs['slug']
        helpful_article = HelpArticle.objects.get(slug=slug)
        helpful_article.view += 1
        helpful_article.save()
        form = HelpfulForm()
        ip = self.request.META.get('REMOTE_ADDR')
        yes = Helpful.objects.filter(help_article=helpful_article, status=True)
        count = Helpful.objects.filter(help_article=helpful_article)
        no = Helpful.objects.filter(help_article=helpful_article, status=False)
        # count =
        helpful = Helpful.objects.filter(help_article=helpful_article, ip=ip)
        context = {
            'helpful_article': helpful_article,
            'form': form,
            'yes': yes,
            'no': no,
            'helpful': helpful

        }

        return super(HelpArticleDetailView, self).get_context_data(**kwargs, **context)


def set_helpful(request):
    form = HelpfulForm(request.POST or None)
    article = HelpArticle.objects.get(id=request.POST.get('help_article'))
    ip = request.META.get('REMOTE_ADDR')
    if request.POST:
        print(form.errors)
        form.ip = ip
        form.help_article = article
        if request.POST.get('status'):
            form.status = False
            form.save()
        elif request.POST.get('status'):
            form.status = False
            form.save()
    next = request.POST.get('next')
    return HttpResponseRedirect(next)

templates/help/help/article_detail.html
{% extends 'help/base.html' %}
{% load static %}
{% block meta %}
    <title>{{ helparticle.title }}</title>
    <meta name="title"
          content="{{ helparticle.title }}">
    <meta name="description"
          content="{{ helparticle.meta_desc }}">
    <meta name="keywords"
          content="{{ helparticle.meta_key }}">
      <link rel="shortcut icon" href="{% static 'assets/images/favicon.ico' %}">
{% endblock meta %}

{% block css %}

{% endblock css %}

{% block content %}

    <div class="col-md-8 padding-20">
        <div class="row">
            <!-- BREADCRUMBS -->
            <div class="breadcrumb-container">
                <ol class="breadcrumb">

                    <li>
                        <a href="{% url 'help:sections_list_url' %}">
                            <i class="fa fa-home"></i>

                        </a>
                    </li>
                    <li>
                        <a href="/help/"> Qo'llanma</a>
                    </li>
                    <li>
                        <a  href="{% url 'help:section_detail_url' helparticle.section.slug %}">{{ helparticle.section.title }}</a>
                    </li>
                    <li class="active">{{ helparticle.title }}</li>
                </ol>
            </div>
            <!-- END BREADCRUMBS -->
            <!-- ARTICLE  -->
            <div class="panel panel-default">

                <div class="margin-bottom-5">
                    <h1 class="article-heading">{{ helparticle.title }}</h1>
                </div>
                <div class="article-info">

                    <div class="art-date">

                        <i class="fa fa-calendar-o"></i> {{ helparticle.pub_date|date }}
                    </div>
                    <div class="art-category">
                        <a href="{% url 'help:section_detail_url' helparticle.section.slug %}">
                            <i class="fa fa-folder"></i> {{ helparticle.section.title }} </a>
                    </div>

                    <div class="art-category">
                        <a href="#">
                            <i class="fa fa-eye"></i> {{ helparticle.view }} </a>
                    </div>

                </div>
                <div class="article-content">
                    {{ helparticle.text|safe }}
                </div>

                <hr class="style-three">
                <div class="article-feedback">
                    <h2>
                        <small>Ushbu maqola foydali bo'ldimi?</small>
                    </h2>

                    <form action="{% url 'help:set_helpful' %}" class="col" style="float: left; margin-right: 10px"
                          method="post">
                        {% csrf_token %}
                        <input type="hidden" name="help_article" value="{{ helparticle.id }}">
                        <input type="hidden" name="status" value="True">
                        <input type="hidden" name="ip" value="127.0.0.1">
                        <input type="hidden" name="next" value="{{ request.path }}">


                        <button type="submit" {% if helpful %}
                                disabled {% endif %}class="btn-success btn-o btn-wide">
                            <i class="fa fa-thumbs-o-up"></i> Ha ({{ yes.count }})
                        </button>
                    </form>

                    <form action="{% url 'help:set_helpful' %}" class="col" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="help_article" value="{{ helparticle.id }}">
                        <input type="hidden" name="status" value="False">
                        <input type="hidden" name="next" value="{{ request.path }}">
                        <input type="hidden" name="ip" value="127.0.0.1">
                        <button type="submit"  {% if helpful %}
                                disabled {% endif %}class="btn-danger btn-o btn-wide"> Yo'q ({{ no.count }})
                            <i class="fa fa-thumbs-o-down"></i>
                        </button>
                    </form>


                </div>
            </div>

        </div>

    </div>
{% endblock content %}


{% block js %}
    <script src="{% static 'js/responsive.js' %}"></script>
    <script>
        $(document).ready(function () {
            $('.article-content').find('img').addClass('img-responsive')

        })
    </script>
{% endblock js %}

templates/help/help/home.html
{% extends 'help/base.html' %}
{% load get_five_articles %}
{% load static %}
{% block meta %}
    <title>Qo'llanma E-RIB.UZ</title>
    <link rel="shortcut icon" href="{% static 'assets/images/favicon.ico' %}">
    <!-- LOADING STYLESHEETS -->
    <meta name="description" content="E-RIB.UZ tizimida professionalga aylaning">
    <meta name="keywords"
          content="E-RIB.UZ, База знаний, Qo'llanma, помощь, проблема, E-RIB.UZ muammo, qanday qilib">
    <link rel="shortcut icon" href="{% static 'assets/images/favicon.ico' %}">
{% endblock meta %}

{% block content %}

    <div class="col-md-8 padding-20">
        <div class="row">
            <!-- BREADCRUMBS -->
            <div class="breadcrumb-container">
                <ol class="breadcrumb">
                    <li>
                        <a href="{% url 'help:sections_list_url' %}">
                            <i class="fa fa-home"></i>
                        </a>
                    </li>
                    <li class="active">Qo'llanma</li>
                </ol>
            </div>
            <!-- END BREADCRUMBS -->
            <!-- ARTICLES CATEGORIES SECTION -->
            <div class="fb-heading">
                Qo'llanma
            </div>


            <hr class="style-three">
            <div class="row">
                {% for section in sections %}
                    <div class="col-md-6 margin-bottom-20">
                        <div class="fat-heading-abb">

                            <a href="{% url 'help:section_detail_url' section.slug %}">
                                <i class="fa fa-folder"></i> {{ section.title }}
                                <span class="cat-count">({{ section.articles.count }})</span>
                            </a>
                        </div>
                        {% for article in section.articles.all|get_five_articles:'sort' %}
                            <div class="fat-content-small padding-left-30">
                                <ul>
                                    <li>
                                        <a href="{% url 'help:article_detail_url' article.slug %}">
                                            <i class="fa fa-file-text-o"></i> {{ article.title }} </a>
                                    </li>
                                </ul>
                            </div>
                        {% endfor %}
                    </div>
                {% endfor %}

            </div>
            <!-- END ARTICLES CATEOGIRES SECTION -->
        </div>
    </div>

{% endblock content %}

templates/help/help/search.html
{% extends 'help/base.html' %}
{% block content %}

    <div class="col-md-8 padding-20">
        <div class="row">
            <!-- BREADCRUMBS -->
            <div class="breadcrumb-container">
                <ol class="breadcrumb">
                    <li>
                        <a href="/help/">
                            <i class="fa fa-home"></i>
                        </a>
                    </li>
                    <li class="active">Qidiruv</li>
                </ol>
            </div>
            <!-- END BREADCRUMBS -->
            <!-- ARTICLES CATEGORIES SECTION -->
            <div class="fb-heading">
                Qo'llanma
            </div>
            <hr class="style-three">
            <div class="row">
                {% if results.count > 0 %}
                    <div class="col-md-12 margin-bottom-20">
                        <div class="fat-heading-abb">

                            <i class="fa fa-search"></i> "{{ request.GET.q|escape }}" qidiruv so'zi orqali
                            <span class="cat-count">({{ results.count }})</span> ta natija topildi

                        </div>
                        <div class="fat-content-small padding-left-30">
                            <ul>
                                {% for result in results %}
                                    <li>
                                        <a href="{% url 'help:article_detail_url' result.slug %}">
                                            <i class="fa fa-file-text-o"></i>{{ result.title }}
                                        </a>
                                    </li>
                                {% endfor %}

                            </ul>
                        </div>
                    </div>
                {% else %}
                    <div class="col-md-12 margin-bottom-20">
                        <div class="fat-heading-abb">

                            <i class="fa fa-search"></i> "{{ request.GET.q|escape }}"  qidiruv so'zi orqali hech nima topilmadi!


                        </div>
                    </div>
                {% endif %}

            </div>
            <!-- END ARTICLES CATEOGIRES SECTION -->
        </div>
    </div>


{% endblock %}

templates/help/help/section_detail.html
{% extends 'help/base.html' %}

{% block content %}

            <!-- ARTICLE OVERVIEW SECTION -->
            <div class="col-md-8 padding-20">
                <div class="row">
                    <!-- BREADCRUMBS -->
                    <div class="breadcrumb-container">
                        <ol class="breadcrumb">
                            <li>
                                <a href="{% url 'help:sections_list_url' %}">
                                    <i class="fa fa-home"></i>
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'help:sections_list_url' %}">Qo'llanma</a>
                            </li>
                            <li class="active">{{ section.title }}</li>
                        </ol>
                    </div>
                    <!-- END BREADCRUMBS -->
                    <!-- ARTICLES -->
                    <div class="fb-heading">
                        <i class="fa fa-folder"></i> {{ section.title }} (Topildi {{ section.articles.count }} ta maqola):
                        <span class="cat-count"></span>
                    </div>
                    <hr class="style-three">

                    {% for article in section.articles.all %}
                    <div class="panel panel-default">
                        <div class="article-heading-abb">
                            <a href="{% url 'help:article_detail_url' article.slug %}">
                                {{ article.title }}
                                </a>
                        </div>



                    </div>
                     {% endfor %}

                </div>
            </div>
            <!-- END ARTICLES OVERVIEW SECTION-->




{% endblock content %}